export {default as imageMap} from './map-point.png';
export {default as woman} from './woman.png';
export {default as uncle} from './uncle.png';
export {default as man} from './man.png';
export {default as sister} from './girl.png';
export {default as brother} from './gamer.png';
export {default as other} from './other.png';
export {default as auntie} from './empathy.png';
export {default as friend} from './user.png';
